server:
  port: 8081

# MongoDB connection URI for Atlas (Spring Data MongoDB)
spring:
  data:
    mongodb.uri: mongodb+srv://mukeshgangwar654:dvbMXOXuNe1UL4e0@family-crop-management.9g0l69v.mongodb.net/family-crop-management?retryWrites=true&w=majority&appName=family-crop-management
